### ISSUE TITLE
Improve User documentation and Client Usage Guide

### ISSUE THREAD

**Issue by viveknigam3003** [rucio/desktop#5]
## Motivation

The usage guide provided with the app in the user documentation is not self-sufficient and seems incomplete. There is also a large scope of improvement by adding more illustrations, GIFs, etc to help the users setup and use the application easily.

## Modification

Improve the user documentation and usage guide for Rucio Desktop by adding more screenshots and GIFs with explanation to use the app and set it up for a first time user.
Contact @viveknigam3003 for more details on this issue.

**Comment by sayang14** [comment]
Hi @viveknigam3003 , Can I hace a try with this issue as a part of hacktoberfest this year? It will be grateful if you help a liite bit on how to proceed since I have Linux(ubuntu) and not debian or centox as mentioned in the requirements. thanks!
